name: tests

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
            main-branch-name: 'master'

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.node-version'
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Starting nx cloud CI
        run: yarn nx-cloud start-ci-run

      - name: Linting
        run: yarn nx affected --target=lint --parallel --max-parallel=3
        timeout-minutes: 10

      - name: Tests
        run: yarn nx affected --target=test --parallel --max-parallel=3 --codeCoverage
        timeout-minutes: 10

      - name: Installing lcov
        run: sudo apt-get install -y lcov

      - name: Merge coverage
        run: find ./coverage -name "lcov.info" | awk '$0="-a "$0' | xargs lcov -o ./coverage/lcov.info

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Stopping nx cloud CI
        run: yarn nx-cloud stop-all-agents
  
  agents:
    runs-on: ubuntu-latest
    name: Agent 1
    timeout-minutes: 60
    
    strategy:
      matrix:
        agent: [1, 2, 3]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
            
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      
      - name: Start Nx Agent ${{ matrix.agent }}
        run: yarn nx-cloud start-agent